test4/booktest/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # 原本是r'^(\d+)/$'这个但是如果变成r'^3(\d+)/$'只有index.html中的<a href="1">就失效了
    url(r'^3(\d+)/$', views.show, name='show'),
    # 反向解析的意思就是说无论这个位置以后改成什么样子都能通过不修改模板中url来保证这个url的有效性
    url(r'^(?P<id1>\d+)/(?P<id2>\d+)/$', views.show_reverse, name='show_reverse'),
    url(r'^index2/$', views.index2, name='index2'),
    url(r'^user1/$', views.user1, name='user1'),
    url(r'^user2/$', views.user2, name='user2'),
    url(r'^htmltest/$', views.htmlzhuanyitest, name='htmltest'),
    url(r'^csrf1/$', views.csrf1, name='csrf1'),
    url(r'^csrf2/$', views.csrf2, name='csrf2'),
    url(r'^verify_code/$', views.verify_code_test, name="verify_code"),
    url(r'^verifytest1/$', views.verifytest1, name="verifytest1"),
    url(r'^verifytest2/$', views.verifytest2, name="verifytest2"),
]

test4/test4/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^booktest/', include('booktest.urls', namespace='booktest'))
]

test4/booktest/models.py
from django.db import models

# Create your models here.
class BookInfo(models.Model):
    btitle = models.CharField(max_length=20)
    bpub_date = models.DateTimeField(db_column='pub_date')
    bread = models.IntegerField(default=0)
    bcomment = models.IntegerField(default=0)
    isDelete = models.BooleanField(default=False)

    class Meta():
        db_table = 'bookinfo'

    def __str__(self):
        return self.btitle

class HeroInfo(models.Model):
    hname = models.CharField(max_length=10)
    hgender = models.BooleanField()
    hcontent = models.CharField(max_length=1000)
    isDelete = models.BooleanField(default=False)
    book = models.ForeignKey('BookInfo')

    def show_name(self):
        return self.hname

test4/booktest/views.py
from django.shortcuts import render, redirect
from .models import HeroInfo, BookInfo
from django.http import HttpResponse


# Create your views here.

def index(request):
    hero_id1 = HeroInfo.objects.get(pk=1)
    hero_list = HeroInfo.objects.filter(isDelete=False)
    context = {'hero': hero_id1,
               'hero_list': hero_list}
    return render(request, 'booktest/index.html', context=context)


def show(request, id):  # 正常解析
    context = {'id': id}
    return render(request, 'booktest/show1.html', context=context)


def show_reverse(request, id1, id2):  # 反向解析
    context = {'id': (id1, id2)}
    return render(request, 'booktest/show.html', context=context)


# 用于练习模板的继承
def index2(request):
    return render(request, 'booktest/index2.html')


# 三层模板继承 #templates中 user1.html和user2.html继承自base_user.html继承自base.html
def user1(request):
    context = {'user1_title': 'user1_title',
               'uname': 'my name is user1'}
    return render(request, 'booktest/user1.html', context=context)


def user2(request):
    context = {'title': 'user12',
               'uname': 'my name is user2'}
    return render(request, 'booktest/user2.html', context=context)


# html转义练习
def htmlzhuanyitest(request):
    '''
    从视图传到模板当中的变量默认是转义的，传什么给模板，模板就输出什么；
    而直接在模板中定义的变量是不经过转义的
    '''
    context = {'t1': '<h1>123</h1>'}
    return render(request, 'booktest/htmltest.html', context=context)


# csrf练习
def csrf1(request):
    return render(request, 'booktest/csrf1.html')


def csrf2(request):
    username = request.POST['username']
    return HttpResponse('username is {}'.format(username))


# 验证码练习
def verify_code_test(request):
    from PIL import Image, ImageDraw, ImageFont
    import random
    # 创建背景色
    bgColor = (random.randrange(50, 100), random.randrange(50, 100), 0)
    # 规定宽高
    width = 100
    height = 25
    # 创建画布
    image = Image.new('RGB', (width, height), bgColor)
    # 构造字体对象
    font = ImageFont.truetype('C:\Windows\Fonts\simfang.ttf', 24)
    # 创建画笔
    draw = ImageDraw.Draw(image)
    # 创建文本内容
    text = '0123ABCD'
    # 逐个绘制字符
    textTemp = ''
    for i in range(4):
        textTemp1 = text[random.randrange(0, len(text))]
        textTemp += textTemp1
        draw.text((i * 25, 0), textTemp1, (255, 255, 255), font)
    request.session['code'] = textTemp
    image.save('D:\png1.png', 'JPEG')
    # 保存到内存流中
    from io import StringIO, BytesIO
    buf = BytesIO()
    image.save(buf, 'png')
    # 将内存流中的内容输出到客户端
    return HttpResponse(buf.getvalue(), 'image/png')

def verifytest1(request):
    return render(request, 'booktest/verifytest1.html')

def verifytest2(request):
    # return render(request, 'booktest/verifytest2.html')
    code = request.POST.get('code')
    session_code = request.session.get('code')
    if code.lower() == session_code.lower():
        # return redirect('/booktest/')
        return HttpResponse('您已登录成功')

test4/templates/booktest/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            title
        {% endblock %}
    </title> {# 这个block在base_user.html中不继承也没关系，在user1.html中仍可以继承 #}
    {% block script_block %}

    {% endblock %}
</head>
<body>
<h1>logo</h1>
<hr>
{% block content1 %}
    <h3> hahahahahah </h3>
{% endblock %}
<hr>
<h1>contact {{ uname }}</h1>
</body>
</html>

test4/templates/booktest/base_goods.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
    <!--<meta charset="UTF-8">-->
    <!--<title>Title</title>-->
<!--</head>-->
<!--<body>-->

<!--</body>-->
<!--</html>-->


{extends 'booktest/base.html'}

{% block content1 %}

    <table border="1">
        <tr>
            <td height="300px" width="200px">推荐商品</td>
            <td height="300px" width="200px">
                {% block user_content %}
                {% endblock user_content %}</td>
        </tr>

    </table>

{% endblock content1 %}

test4/templates/booktest/base_user.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--<meta charset="UTF-8">-->
<!--<title>Title</title>-->
<!--</head>-->
<!--<body>-->

<!--</body>-->
<!--</html>-->

{% extends 'booktest/base.html' %}

{% block title %}
    用户中心
{% endblock %}

{% block content1 %}
    <table border="1">
        <tr>
            <td height="300px" width="200px">用户导航</td>
            <td height="300px" width="200px">
                {% block user_content %}
                {% endblock user_content %}</td>
        </tr>
    </table>
{% endblock content1 %}

test4/templates/booktest/csrf1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>csrf1</title>
</head>
<body>
<form action="/booktest/csrf2/" method="post">
    {% csrf_token %}
    用户名：<input type="text" name="username" value="wsj">
    <input type="submit" value="submit">
</form>
</body>
</html>

test4/templates/booktest/htmltest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>
    {{ t1|escape }} {# 默认就有escape，表示转义 #}
</div>
<div>
    {{ t1|safe }} {# safe表示不进行转义 #}
</div>
<div>
    {% autoescape off %} {# autoescape用off或on控制是否转义 off表示不转义#}
        {{ t1 }}
    {% endautoescape %}
</div>
<div> {# 手动转义 #}
    手动转义<br>
    {{ t1|default:"&lt;h1&gt;123&lt;/h1&gt;" }}
    {# 表示如果t1存在则输出t1的值，如果不存在则输出default后面的值 #}
</div>
<div>
    {{"&amplt;h1&ampgt;123&amplt;/h1&ampgt;"}}
</div>
</body>
</html>

test4/templates/booktest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
</head>
<body>
{% comment %}
https://blog.csdn.net/xyp84/article/details/7945094
{% endcomment %}
{{hero.show_name}}
<br>
============================================================
<ul>
{% for hero in hero_list %}
    {% if forloop.counter|divisibleby:"2" %} {#使用过滤器#}
        <li style="background-color: crimson; width: 70px">{{forloop.counter}}:{{hero.show_name}}</li>
    {% else %}
        <li style="color: blue">{{forloop.counter}}:{{hero.show_name}}</li>
    {% endif %}
{% empty %}
    <li>啥也没找到</li>
{% endfor %}
</ul>
<br>

=====================反向解析=========================
<br>
<a href="123/">显示（正常解析）(因为这个时候是写的绝对路径(而django中建议写成绝对路径)，当url.py中的url解析改变时，这个链接就失效了)</a>
<br>
{% comment %}
{% url 'booktest:show' %} 解析成--> booktest/(\d+)
{% endcomment %}
<a href="{% url 'booktest:show_reverse' '123' '777'%}">显示（反向解析）(反向解析解决了因为写成绝对路径，而后面因为url改变匹配不到路径的问题)</a> {#'123'为传递进去的参数 #}
{#<a href="1/2">asldfjalsdfj</a>#}
</body>
</html>

test4/templates/booktest/index2.html
{% extends 'booktest/base.html' %}

{% block title%}
    this is index2
{% endblock title %}

{% block content1%}
<h3>this is content from index2</h3>
{% endblock content1 %}

test4/templates/booktest/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>show</title>
</head>
<body>
{{id}}
</body>
</html>

test4/templates/booktest/show1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>show1</title>
</head>
<body>
{{id}}
</body>
</html>

test4/templates/booktest/user1.html
{% extends 'booktest/base_user.html' %}

{% block title %}
    {{ user1_title }} {# 注意传进来的context的键不能与block的标签名一致，不会出错但是会导致不能显示想要显示的内容 #}
{% endblock %}

{#{% block script_block %}#}
{#    <script>alert('123')</script>#}
{#{% endblock %}#}

{% block user_content %}
用户中心1
{% endblock user_content %}

test4/templates/booktest/user2.html
{% extends 'booktest/base_user.html' %}

{% block user_content %}
<h1>用户中心2</h1>
{% endblock user_content %}

test4/templates/booktest/verifytest1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>verifytest1</title>
</head>
<body>
<form action="/booktest/verifytest2/" method="post">
    {% csrf_token %}
    <img src="/booktest/verify_code/" alt="this is a pic">
    <input type="text" name="code" value="please input text">
    <input type="submit" value="提交">
</form>
</body>
</html>